[package]
name = "harboria-core"
version.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
harboria-embodiment.workspace = true
harboria-execution.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
